// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU6EhutdpRHuOqFJBNFXTHQRnC0x5t8l8',
    appId: '1:878470997474:web:e74bea814ee3906c4445bb',
    messagingSenderId: '878470997474',
    projectId: 'farmindv2',
    authDomain: 'farmindv2.firebaseapp.com',
    storageBucket: 'farmindv2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfJqFyOmv13pD4MiQV2Kyuldv-wu8KCvo',
    appId: '1:878470997474:android:b4327b628db047c74445bb',
    messagingSenderId: '878470997474',
    projectId: 'farmindv2',
    storageBucket: 'farmindv2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOieGLP7rRsX4blpS4Ub0HdXxqhU_RCmQ',
    appId: '1:878470997474:ios:43a4100d4912055c4445bb',
    messagingSenderId: '878470997474',
    projectId: 'farmindv2',
    storageBucket: 'farmindv2.appspot.com',
    iosBundleId: 'com.example.farmind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU6EhutdpRHuOqFJBNFXTHQRnC0x5t8l8',
    appId: '1:878470997474:web:5b748a9234bf432b4445bb',
    messagingSenderId: '878470997474',
    projectId: 'farmindv2',
    authDomain: 'farmindv2.firebaseapp.com',
    storageBucket: 'farmindv2.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOieGLP7rRsX4blpS4Ub0HdXxqhU_RCmQ',
    appId: '1:878470997474:ios:43a4100d4912055c4445bb',
    messagingSenderId: '878470997474',
    projectId: 'farmindv2',
    storageBucket: 'farmindv2.appspot.com',
    iosBundleId: 'com.example.farmind',
  );

}